### PR TITLE
Merge attempt #1 :)

### PR DESCRIPTION
**Pull request by urban-1**
Hi,

This looks messy and probably better to be merged in another branch (as you said - #1 )

Now, the main changes:

- Base64 encoding for password in `remoteEdit.json`
- Stars (or blanked chars) for passwords in dialogs
- Better `isConnected()` host function and new `ssh2` version
- SFTP create, delete, rename and cut/paste functionality
- Adding file-filter on top of the folder-view which also works as location bar when given a correct remote path
- Tree-view for the currently open files (showing the closest 2 ancestors - `kate` (KDE) style. 
- Handling file re-opening and multiple remotes
- Notification level settings and filtering
- Porting `Q` to `Promises`
- Handling remote host re-connect when editor is left open for long time
- Using `rwlock` in an attempt to avoid corrupted `remoteEdit.json` (did not see that for a while)

This merge is messy as expected... let me know if you prefer me to do the merge given that I added most of the code. Ping me for any questions.

Cheers,
Andreas

### CODE REVIEW

**Comment by newinnovations** [comment]
Let me play around with it. There are some conflicts, some will be trivial others may require some tinkering. May take a couple of days as I have little spare time at the moment.

**Comment by urban-1** [comment]
Cool, no rush :)

**Comment by newinnovations** [comment]
I created a new branch devel which incorporates your PR and some fixes/adaptations. Now it is time to test ;-)

**Comment by urban-1** [comment]
Hello! How are things?

I see you have patched the devel branch. I have not encountered any new problems so far*. Do you think that we can release this on master and thus as atom.io package?

*I once saw my remoteEdit.json being all messed up. This is not a new issue - I have tried to fix this with `rwlock` before and I though I was successful ... but maybe it needs another try.

**Comment by newinnovations** [comment]
Yeah I was testing and waiting for your feedback. I will roll this version out to the main branch in a few days so it will become available on atom.io. The problem I had with the remoteEdit.json file was that the patches expected a new parameter (password) that was not there in the main branch. The loading routines did not handle this well, so all hosts got lost in the upgrade. That was fixed.

**Pull request merged**
