### PR TITLE
Feature: files view keyboard

### PR DESCRIPTION
**Pull request by urban-1**
Last one from me for a while :)

- Enables up, down, enter and backspace within the files-view
- Introduces `Alt+r f` for giving focus to the files-view (usually from the main edit pane)
- Fixes file selection CSS issue in tree-view
- Merges `openDirectory` and `populate` methods of files-view. The first was a thin wrapper of the second one. Now there is only one method (`openDirectory`)

Has been briefly testes in atom 1.23.3 and 1.25.0

### CODE REVIEW

**Comment by newinnovations** [comment]
Sounds great Andreas. Will do some testing as well.

**Comment by newinnovations** [comment]
I have been testing it for a day and while very happy with the new navigation I found a few small problems:

- I cannot see whether the remote file pane has focus or not. The project pane shows this by the color of the selection bar (in my case blue with focus grey without)

- In general it would be better for the default selection to be the first file rather than the ".." directory

- When a file is opened it looses the selection. With <kbd>Alt+r f</kbd>, the ".." directory is selected. I would prefer the file to stay selected.

- When a file is selected but not opened (by clicking it with the mouse) and the pane loses focus, <kbd>Alt+r f</kbd> selects both the ".." directory and the file. The cursor keys move both selections. (This can be repeated to have even more files selected)

- It would be nice if the <kbd>Alt+r m</kbd> command would select the file from the current tab.

**Comment by urban-1** [comment]
Hi, the first 4 bullet-points should be implemented in the latest commit (all fairly fast fixes). <kbd>Alt+r m</kbd> needs some work (I will try to look into it today)

**Comment by newinnovations** [comment]
You work fast Andreas ;-) 

I noticed another problem today: when you open host A using <kbd>Alt+r b</kbd> and close the pane using <kbd>Alt+r v</kbd>, you cannot re-open host A using <kbd>Alt+r b</kbd>. You have to first open another host, before you can re-open host A using <kbd>Alt+r b</kbd>.

I think there was also an occasion that I could not re-open the pane using <kbd>Alt+r v</kbd>, but I cannot reproduce that.

**Comment by urban-1** [comment]
Morning @newinnovations,

Lately got some spare time (your chance to ask for features! :) )

Regarding re-connecting to a host: The main problem was the logic with `setHost` method in combination with the fact that some async methods did not accept `callback`s. I have changed this for `connect`, `openDirectory` and `setHost`. The code still has a combination of "default behavior" and callbacks which we might need to clean up later... 

The reconnect bug should be gone now and I have tested the navigation shortcuts with files opened from multiple remote hosts (sftp only). Let me know if things work for you.

**Comment by newinnovations** [comment]
For me the <kbd>Alt+r m</kbd> is not working: nothing gets selected. And I had a corrupted remoteEdit.json today (some strange trailing data) ... I have not had corruption before (only an empty file during upgrade caused by missing password entries)

Talking about features :-)
- Escape to close the pane
- A close button in the header similar to the editor tabs
- The header saying "Remote edit" instead of "Open files"
- The separator bar between open files and the remote directory cannot be moved/dragged

**Comment by urban-1** [comment]
<kbd>Alt+r m</kbd>, given that the current tab/editor is a remote file, should:

- Give focus to the files-view
- Open the correct remote directory
- Select the file currently open

Do you have any errors in the console? I can try to record a

Now, regarding the corrupted remoteEdit.json: I have seen this before. Its some extra data (like a cut in half json object) are appended at the end. I am not able though to reproduce and thus difficult to fix. There were reports in the original remote-edit that a "reload" using developer tools, causes the file to get empty! That I have seen and I think I could look into.. Alternatively, I was thinking of replacing it with a sqlite file altogether :)

Features wise, can we raise them as issues to track them? I am not sure I get what the first two refer to

**Comment by urban-1** [comment]
Hi again, just realised that <kbd>Alt+r m<kbd> invokes `remote-edit:browse-more` (depending on the platform)

Do you want me to re-bind to `remote-edit:reveal-in-browser`? Or enhance the browse-more view (I have never used it tbh! )

**Comment by newinnovations** [comment]
Andreas, what is the status?  I have tested it today and it all seems fine and I would like to merge and release it. However your commit 7431fbec31a3125b7706ae684022090f894a8df2 suggests there may be an issue?

I found a minor issue: when you reopen atom and open the pane, the "open files" list does not get populated. Files appear after you click on their tabs.

**Comment by urban-1** [comment]
Hi, this should be ready for merging.

Re the commit I took back, I was trying to allow for selection on the tree-view (top) in a similar way with the default tree-view, however, I am struggling a lot with the CSS there. The commented out styles are working fine... until vertical scroll-bars appear, in which case the list scrolls but the selection (:before element) is left behind! This is a different problem all together and I shouldn't have tried to push a fix in this merge :)

I think we are good to merge this one (and maybe create an issue for the reopening)

**Pull request merged**
